version: 2
jobs:
  build:
    working_directory: ~/personal_app
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .main }}-{{ checksum "yarn.lock" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .main }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: yarn start

